# -*- coding: utf-8 -*-
"""lab02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l2KnVlcxHkPyZpX-9-YeMSHVeWPhfvwx

1. Przygotowanie danych
"""

from sklearn.datasets import fetch_openml
import numpy as np
mnist = fetch_openml('mnist_784', version=1)

print((np.array(mnist.data.loc[42]).reshape(28,28)>0).astype(int))

"""2. Zbiór uczący i testowy"""

X, y = mnist["data"], mnist["target"].astype(np.uint8)
print(X.shape, y.shape)

y = sorted(y)
X.reindex()

X_train, X_test = X[:56000], X[56000:]
y_train, y_test = y[:56000], y[56000:]

print(set(y_train))
print(set(y_test))

from sklearn.model_selection import train_test_split
X, y = mnist["data"], mnist["target"].astype(np.uint8)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""3. Uczenie, jedna klasa"""

from sklearn.linear_model import SGDClassifier
y_train_0 = (y_train == 0)
y_test_0 = (y_test == 0)

sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train, y_train_0)

from sklearn.model_selection import cross_val_score

cva = cross_val_score(sgd_clf, X_train, y_train_0, scoring="accuracy", n_jobs=-1, cv=3)

acc_train = sgd_clf.score(X_train, y_train_0)
acc_test = sgd_clf.score(X_test, y_test_0)

import pickle
with open("sgd_cva.pkl", 'wb') as f:
    pickle.dump(cva, f)

with open("sgd_acc.pkl", 'wb') as f:
    pickle.dump([acc_train, acc_test], f)

"""5. Uczenie, wiele klas"""

svm_clf = SGDClassifier()
svm_clf.fit(X_train, y_train)

from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix

y_train_pred = cross_val_predict(svm_clf, X_train, y_train, cv=3, n_jobs=-1)
conf_mx = confusion_matrix(y_train, y_train_pred)

with open("sgd_cmx.pkl", 'wb') as f:
    pickle.dump(conf_mx, f)