# -*- coding: utf-8 -*-
"""lab01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-nOONMmsTy1rchZh-NuTCh9zWm9neyeb

1.3 Informacje o zbiorze danych
"""

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('data/housing.csv.gz')
df.head()
df.info()

df.ocean_proximity.value_counts()

df.ocean_proximity.describe()

"""1.4 Wizualizacja"""

df.hist(bins=50, figsize=(20, 15)).savefig("obraz1.png")

df.plot(kind="scatter", x="longitude", y="latitude",alpha=0.1, figsize=(7,4)).savefig("obraz2.png")

df.plot(kind="scatter", x="longitude", y="latitude",alpha=0.4, figsize=(7,3), colorbar=True,s=df["population"]/100, label="population",c="median_house_value", cmap=plt.get_cmap("jet")).savefig("obraz3.png")

"""1.5 Analiza"""

df.corr()["median_house_value"].sort_values(ascending=False).reset_index().rename(columns={"index":"atrybut", "median_house_values":"wspolczynnik_korelacji"}).to_csv("korelacja.csv", index=False)

import seaborn as sns
sns.pairplot(df)

"""1.6 przygotowanie do uczenia"""

from sklearn.model_selection import train_test_split
train_set, test_set=train_test_split(df,test_size=0.2,random_state=42)
len(train_set),len(test_set)

train_set.to_pickle("train_set.pkl")
test_set.to_pickle("test_set.pkl")

