# -*- coding: utf-8 -*-
"""lab07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1syLI0tBxJaG252IYx__3-B6PUfs6Q4g_
"""

import pickle
from sklearn.datasets import fetch_openml
from sklearn.cluster import KMeans, DBSCAN
from sklearn.metrics import silhouette_score, confusion_matrix
import numpy as np

"""1. Przygotowanie danych"""

mnist = fetch_openml('mnist_784', version=1, as_frame=False, parser='auto')
mnist.target = mnist.target.astype(np.uint8)
X = mnist['data']
y = mnist['target']

"""2. KMeans"""

km8 = KMeans(n_clusters=8, n_init=10)
km9 = KMeans(n_clusters=9, n_init=10)
km10 = KMeans(n_clusters=10, n_init=10)
km11 = KMeans(n_clusters=11, n_init=10)
km12 = KMeans(n_clusters=12, n_init=10)

km8.fit(X)
km9.fit(X)
km10.fit(X)
km11.fit(X)
km12.fit(X)

y_km8 = km8.predict(X)
y_km9 = km9.predict(X)
y_km10 = km10.predict(X)
y_km11 = km11.predict(X)
y_km12 = km12.predict(X)

silhouette = [silhouette_score(X, km8.labels_), silhouette_score(X, km9.labels_), silhouette_score(X, km10.labels_), silhouette_score(X, km11.labels_), silhouette_score(X, km12.labels_)]
with open('kmeans_sil.pck', 'wb') as f:
    pickle.dump(silhouette, f)

matrix = confusion_matrix(y, y_km10)

array = np.argmax(matrix, axis=1)
array = np.sort(array)
array = np.unique(array)

with open('kmeans_argmax.pck', 'wb') as f:
    pickle.dump(array, f)

"""3. DBSCAN"""

dists = []
for i in range(300):
    x1 = X[i]
    for j in range(len(X)):
        if i != j:
            x2 = X[j]
            dist = np.linalg.norm(x1 - x2)
            if dist != 0:
                dists.append(dist)

eps_values = sorted(dists)[:10]

with open('dist.pkl', 'wb') as f:
    pickle.dump(eps_values, f)

eps_mean = np.mean(eps_values[:3])
array = np.array([], dtype=np.int32)
for eps in np.arange(eps_mean, eps_mean+eps_mean * 0.1, eps_mean * 0.04):
    dbscan = DBSCAN(eps)
    clusters = dbscan.fit_predict(X)
    clusters = len(set(clusters))
    array = np.append(array, clusters)

with open('dbscan_len.pkl', 'wb') as f:
    pickle.dump(array, f)

